# Generated by Django 2.2.6 on 2019-10-28 12:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sayfa Adı')),
                ('url', models.CharField(max_length=200, verbose_name="Sayfa Url'i")),
                ('is_it_in_navbar', models.BooleanField(default=False, verbose_name="Navbar'da linki olacak mı?")),
                ('page_content', ckeditor.fields.RichTextField(verbose_name='Sayfa İçeriği')),
            ],
        ),
    ]
