# Generated by Django 2.2.12 on 2020-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rütbe'),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Puan'),
        ),
    ]
